# Generated by Django 4.1.1 on 2022-09-23 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Опубликовано'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=users.utilities.get_timestamp_path, verbose_name='Заявка')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.record', verbose_name='Заявки')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация',
                'verbose_name_plural': 'Дополнительные иллюстрации',
            },
        ),
    ]
