# Generated by Django 4.1.1 on 2022-09-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_additionalimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_at'], 'permissions': (('can_mark_returned', 'Set record as returned'),), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='record',
            name='add_image',
            field=models.ImageField(blank=True, upload_to='media/images/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='record',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
