# Generated by Django 4.1.1 on 2022-09-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_bio_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category of record', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description of the record', max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(blank=True, choices=[('n', 'Новая'), ('p', 'Выполнено'), ('a', 'Принято в работу')], default='n', help_text='Record availability', max_length=100)),
                ('category', models.ManyToManyField(help_text='Select a genre for this book', to='users.category')),
            ],
        ),
    ]
