# Generated by Django 4.1.1 on 2022-09-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(upload_to='media/images/%Y-%m-%d/'),
        ),
    ]
